provider: gemini-native
model_name: gemini-1.5-pro
max_tokens: 100
timeout: 30

prompt_template: |
  Based on the following git diff, generate a concise commit message that follows conventional commits format:

  $diff

  Generate only the commit message, no additional text.

additional_params:
  temperature: 0.3
