additional_params:
  temperature: 0.3
  top_p: 1.0
api_key: ${OPENAI_API_KEY}
max_tokens: 100
model_name: gemini-1.5-pro
prompt_template: 'Based on the following git diff, generate a concise commit message
  that follows conventional commits format:


  $diff


  Generate only the commit message, no additional text.

  '
provider: gemini-cli
timeout: 30
